### ISSUE TITLE
syllabus pdf not rendering

### ISSUE THREAD

**Issue by ahuoguo** [gmcninch-tufts/2024-Sp-Math190#1]
Hi Geroge,

The course info pdfs are not showing up (eg this [link](https://gmcninch-tufts.github.io/2024-Sp-Math190/course-pages/Math190--course-syllabus.pdf) on this [course info page](https://gmcninch-tufts.github.io/2024-Sp-Math190/course-pages/Math190--course-info.html))

Based on the log for github workflow, it seems like pdfs are only uploaded to the domain in the `/course-assets` directory. So I think you can move the pdf there and update the markdown in `/course-pages`
https://gmcninch-tufts.github.io/2024-Sp-Math190/course-assets/Spence--Supplementary-material-for-coding-Theory.pdf

**Comment by gmcninch-prof** [comment]
Thanks. The `pdf`s for the syllabus (etc) are build from the markdown files found in `/course-pages` (via `pandoc`). I could probably re-craft the `Makefile` to instead create the `pdf` files in `/course-assets`, but I found a way to just have them served in-place.

**Comment by gmcninch-prof** [comment]
(I think this is settled)
